### ISSUE TITLE
Error in module

### ISSUE THREAD

**Issue by michelelazzarato** [eyesore/appc-android-bluetooth#4]
Hi,
 I try to use your module in my simple project but when I run your sample code this error appear:

[WARN] :   W/System.err: java.lang.NullPointerException: Attempt to get length of null array
[WARN] :   W/System.err: 	at com.eyesoreinc.bluetooth.BluetoothService.getServiceDescriptions(BluetoothService.java:340)
[WARN] :   W/System.err: 	at com.eyesoreinc.bluetooth.BluetoothService.getServiceList(BluetoothService.java:302)
[WARN] :   W/System.err: 	at com.eyesoreinc.bluetooth.BluetoothModule.getDeviceServices(BluetoothModule.java:275)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:921)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1144)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:363)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:135)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5491)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
[ERROR] :  Error in bluetooth module:
[INFO] :   0:  "Attempt to get length of null array"
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0076}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0077}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0064}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006d}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006e}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x1801 a=3 r=0x7f080038}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x1201 a=3 r=0x7f080039}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x1801 a=3 r=0x7f080038}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006f}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0070}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0065}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0066}
[WARN] :   Resources: Converting to string: TypedValue{t=0x1c/d=0x33ffffff a=3 r=0x7f0b0032}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0067}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0068}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x1801 a=3 r=0x7f080038}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x1801 a=3 r=0x7f080038}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0069}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006a}
[WARN] :   Resources: Converting to string: TypedValue{t=0x1c/d=0x33ffffff a=3 r=0x7f0b0032}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006b}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c006c}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0062}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x3001 a=3 r=0x7f080000}
[WARN] :   Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0c0063}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x3001 a=3 r=0x7f080000}
[WARN] :   Resources: Converting to string: TypedValue{t=0x5/d=0x3001 a=3 r=0x7f080000}
[INFO] :   HAL: loaded HAL id=gralloc path=/system/lib/hw/gralloc.mt8163.mali.so hmi=0x0 handle=0xf21a6544
[INFO] :   I/[MALI][Gralloc]: [+]r_hnd:0xf7dad368, fd:47, ion_hnd(0x5), req_format(0x1), int_fmt(0x1)  byte_stride(1408), flags(0x4), usage(0xb00), size(1208064), alloc_size(1208064) 338(352)X858(858) pid(31301)  sec (0)
[INFO] :   HAL: loaded HAL id=gralloc path=/system/lib/hw/gralloc.mt8163.mali.so hmi=0x0 handle=0xf21a6544
[INFO] :   I/[MALI][Gralloc]: [+]r_hnd:0xf7d0e2e0, fd:46, ion_hnd(0x6), req_format(0x1), int_fmt(0x1)  byte_stride(1408), flags(0x4), usage(0xb00), size(1208064), alloc_size(1208064) 338(352)X858(858) pid(31301)  sec (0)

Can you help me to solve problem?
Thanks in advance,

  Michele.

**Comment by trey-jones** [comment]
It looks like it could be as simple as not having any discoverable bluetooth devices available (length 0 array).  That's the best insight I have based on the logs.  This module is not actively developed currently.

**Comment by michelelazzarato** [comment]
Hi Jones,
 is there a valid module developed for android?
Thanks in advance,

   Michele.

**Comment by trey-jones** [comment]
This library has been used successfully with Titanium up through SDK version 6.  Beyond that I can make no guarantees, nor can I offer to do any troubleshooting currently.  If you want to troubleshoot and make a pull request, we will welcome it!  

You can look at forks of this repository - one of them may be more active than this one.

**Comment by michelelazzarato** [comment]
Hi Jones,
  Thanks for your reply but unfortunately I'm not android developer.
Is there another way for BLE communication in android using Appcelerator?
best regards,

   michele.

**Comment by trey-jones** [comment]
I'm not sure.  FYI, this library was written before LE APIs were available, and does not use them.
